version: "1.0"

services:
  ymdb:
    container_name: ymdb-service
    restart: unless-stopped
    build: .
    ports:
      - "3000:3000"
    # entrypoint: ["npm","run","start:dev"]
    environment:
      NODE_ENV: development
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: ymdb
    networks:
      - ymdb-network
    depends_on:
      - postgres
    volumes:
      - ./:/app
      - /app/node_modules
    
  
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    restart: unless-stopped
    environment: 
      DB_USER: postgres
      DB_PASS: postgres
      POSTGRES_DB: ymdb
    ports:
      - "5432:5432"
    expose:
      - 5432
    networks:
      - ymdb-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "80:80"
    expose:
      - 80
    volumes:
      - ./pgdata/pgadmin:/root/.pgadmin
    networks:
      - ymdb-network
    env_file:
      - .env
volumes:
  postgres_data: {}
  app: {}
networks:
  ymdb-network: